"""phase 2: universities, applications, application_jobs

Revision ID: 5f641ecfb811
Revises: 1026b4a0314a
Create Date: 2026-05-05 01:07:44.536610

"""

from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5f641ecfb811"
down_revision: Union[str, Sequence[str], None] = "1026b4a0314a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
